### ISSUE TITLE
What data should we return in the response?

### ISSUE THREAD

**Issue by awolfe76** [cfpb/grasshopper#1]
Would like to figure out what data we should return to the user in the response? I think that if we figure out what a single address query response looks like it point us in a good direction toward a batch response (start small). This could include things like rank, source, x/y ... but that's what this issue is for.

Some current examples:
Google - https://developers.google.com/maps/documentation/geocoding/#GeocodingResponses
Mapbox - https://www.mapbox.com/developers/api/geocoding/
Census (PDF!) - http://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.pdf
Bing - https://msdn.microsoft.com/en-us/library/ff701714.aspx#code-snippet-10

**Comment by hkeeler** [comment]
There's an example of the ersi "GeoService REST Spec" on  https://github.com/cfpb/grasshopper/issues/18 as well.

**Comment by jmarin** [comment]
Closing, discussion moved elsewhere
