### ISSUE TITLE
Standardize log format and level

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#105]
Review logging for each application, applying logging level as appropriate

**Comment by hkeeler** [comment]
We have two issues named "Review logging".  Renaming this one to "Standardize log format and level".

**Comment by jmarin** [comment]
@hkeeler Can we close this one?

**Comment by hkeeler** [comment]
Here's where we stand with log message formatting:
1. The following write to stdout and are parsable to by logstash:
   1. All of the Scala-based `grasshopper` services's standard logging
   2. `grasshopper-parser`'s Gunicorn access logs
   3. `grasshopper-ui`'s Nginx access logs
2. The following are in an unknown state:
   1. `grasshopper-parser`'s Python logging.  It's setup to log to stdout, but I'm not doing any internal logging, so I haven't set this up.  I'm pretty sure it would not be parsable by logstash out-of-the-box, but should be simple to setup.
   2. I have not tested `grasshopper-loader` and `grasshopper-retreiver` logging.  @wpears was refactoring to a standard NodeJS logging package, but I am not sure of the status of that.  @wpears?
3. The following are known to not currently work:
   1. Scala-based access logs.  Issue #113 has been opened for this.

So, if this issue if for just the `grasshopper` project, yes, we can close this out.  If we consider it for the whole project, then it looks like it needs a little work.
