### ISSUE TITLE
API suggestions

### ISSUE THREAD

**Issue by awolfe76** [cfpb/grasshopper#115]
Based on https://github.com/cfpb/grasshopper/blob/master/docs/geocoder_public_api_spec.md, I'm suggesting the following _(comments and line breaks for clarity)_:

```
{
  // overall status - result(s) returned
  "status": "OK",

  // *might* be useful to know which services returned results
  "addressPointsStatus": "OK",
  "censusServiceStatus": "OK",

  "query": {
    "input": "200 President St Arkansas City AR 71630",
    "parts": {
      "city": "Arkansas City",
      "zip": "71630",
      "state": "AR",
      "streetName": "President St",
      "addressNumber": "200"
    }
  },

  // all results as features
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [-91.19978780015629, 33.608091616155995, 0.0]
      },
      "properties": {
        "address": "200 President St Arkansas City AR 71630",
        "alt_address": "",
        "load_date": 1428674545528,
        "service": "addressPoints"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [-91.19960153268617, 33.60763673811005, 0.0]
      },
      "properties": {
        "RFROMHN": "100",
        "RTOHN": "498",
        "ZIPL": "",
        "FULLNAME": "President St",
        "LFROMHN": "",
        "LTOHN": "",
        "ZIPR": "71630",
        "STATE": "AR",
        "service": "censusService"
      }
    }
  ]
}
```

I'm suggesting the service be listed as `features[x].properties.service` but it could make sense in other places.

Should the censusSerivce provide the city as well? In the UI we would output the returned Census address as something like:
`100 - 498 President St [Arkansas City] AR 71630`
We can get the city from `query.parts.city` but was curious if it could be in the feature as well.

**Comment by hkeeler** [comment]
I like @awolfe76's approach.  With this model, the client code doesn't have to change much as we add new services, unless they want to take advantage of the service-specific `properties`.  This makes me wonder if we even want such implementation details leaking out?  If we make it more generic, then clients _really_ don't have to care (or know about) our child services.  

The only issue I see with @awolfe76 model is `addressPointService` and `censusServiceStatus` attributes.  With those attributes at that level, we'd still have to make client-side changes for any new service we add.  Perhaps we assume a service is "OK" so long as it returns results, and perhaps a `warnings` section where we describe why any given data sources were not available.

I think we should also shift "service" to "data source".  End users care more about where the data came from than our underlying services.

It could be as simple as:

``` json
{
  "status": "OK",
  "query": {
    "input": "200 President St Arkansas City AR 71630",
    "parts": {
      "city": "Arkansas City",
      "zip": "71630",
      "state": "AR",
      "streetName": "President St",
      "addressNumber": "200"
    }
  },
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [-91.19978780015629, 33.608091616155995, 0.0]
      },
      "properties": {
        "source": "state-address-points"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [-91.19960153268617, 33.60763673811005, 0.0]
      },
      "properties": {
        "source": "census-tiger"
      }
    }
  ]
}
```

**Comment by awolfe76** [comment]
I like what @hkeeler has there.

Would still like the `address` to come back as a property though too (not sure if you meant to leave it off or not). It could be different than the query.

In the case of tiger data the address could be cleaner (see below) which would require a bit of working to piece it together nicely on the backend.

```
{
  "status": "OK",
  "query": {
    "input": "200 President St Arkansas City AR 71630",
    "parts": {
      "city": "Arkansas City",
      "zip": "71630",
      "state": "AR",
      "streetName": "President St",
      "addressNumber": "200"
    }
  },
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [-91.19978780015629, 33.608091616155995, 0.0]
      },
      "properties": {
        "source": "state-address-points",
        "address": "200 President St Arkansas City AR 71630"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [-91.19960153268617, 33.60763673811005, 0.0]
      },
      "properties": {
        "source": "census-tiger",
        "address": "200-400 President St Arkansas City AR 71630"
      }
    }
  ]
}
```

**Comment by wpears** [comment]
Somewhat off-topic: where is the `0.0` Z coordinate value getting introduced?
