### ISSUE TITLE
Grasshopper `client` URL Handling

### ISSUE THREAD

**Issue by hkeeler** [cfpb/grasshopper#118]
As discussed on https://github.com/cfpb/grasshopper/pull/116#discussion_r33518936:

> 1. I don't think we should allow upstream services to forward their URL fragments and params through to the  clients.  In general, each URL param (`suggest`) should correlate to a parameter on the underlying function (`geocode()`).  This also means any URL encode/decode logic would also be handled upstream as well.
> 2. We should be using a lib for parsing and building URIs.  As it stands now, the `suggest` logic wouldn't even get picked up if it wasn't the first param, and any additional params would be considered part of the address string.  Looks like Akka HTTP has a nice [`Uri`](http://doc.akka.io/api/akka-stream-and-http-experimental/1.0-RC4/index.html#akka.http.scaladsl.model.Uri) for building.  Not sure why it doesn't parsing too.  There's probably some other class for that. :)  
> 3. When this runs through a reverse proxy, the exact path may not be `/addesses/points/`.  It's probably worth adding a `basepath` to the `application.conf` so it can be overridden as an envvar.

**Comment by jmarin** [comment]
Closing, probably not relevant anymore as a result of refactoring out the HTTP services
