### ISSUE TITLE
Geocoding API docs

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#13]
Public documentation for developers

**Comment by netplusdesign** [comment]
Reference to checklists, best practices, standards, usability testing for APIs, etc…

http://18f.github.io/API-Usability-Testing/pages/lessons_learned

**Comment by hkeeler** [comment]
Here's the "HMDA API Docs" site mentioned at today's standup:
- http://cfpb.github.io/api/hmda/

**Comment by awolfe76** [comment]
Plenty of good examples:
https://stripe.com/docs/api#intro
https://docs.connect.squareup.com/
https://dev.twitter.com/overview/documentation

**Comment by netplusdesign** [comment]
And don't forget MailChimp...
https://apidocs.mailchimp.com/gettingstarted/connectivity.php

**Comment by awolfe76** [comment]
:+1: Thanks @netplusdesign
