### ISSUE TITLE
docker-compose not working correctly

### ISSUE THREAD

**Issue by awolfe76** [cfpb/grasshopper#146]
I was working on this [issue](https://github.com/cfpb/grasshopper-ui/issues/60) and wanted to test before creating the PR. (I'll do the PR anyway because it was so minor.) After pulling down all new code from the other grasshopper projects the containers are built and started properly. _I also ran `sbt clean assembly` first._

But, I get a 502 - Bad Gateway when making the call to the geocoder.

I can see that /status for the parser, census, and addresspoints but I can't on the geocoder.

I attempted to change around the ports in docker-compose because I thought it might have been related to this [grasshopper-ui PR](https://github.com/cfpb/grasshopper-ui/pull/59).

**Comment by hkeeler** [comment]
@awolfe76, I'm fairly certain this _is_ a port mismatch issue.  [`docker-compose-common.yml`](https://github.com/cfpb/grasshopper/blob/master/docker-compose-common.yml#L4) is exposing `geocoder` as 8080, but grasshopper-ui's [`nginx.conf`](https://github.com/cfpb/grasshopper-ui/blob/master/nginx/nginx.conf#L19) is expecting it to be on 31010.

I tried to fix this, but I'm still getting a 502 error, and Nginx is reporting a "connection refused".  Strange.   I'll keep working at it.

**Comment by awolfe76** [comment]
@hkeeler yeah, I was doing the same thing the other day and getting the same problem. Tried several different port configurations and nothing seemed to do it.

**Comment by hkeeler** [comment]
I know what's up, and have it fixed locally.  This is a container vs. host port mismatch.  When running in Compose, the containers attempt to connect on the container port, which is 8080, but Nginx is looking at host port 31010.  When this is running in through Marathon, we set the `servicePort` to 31010, and that port gets exposed in the load balancer, and the container port never comes into play.

I'm switching the geocoder to listen on 31010, and tweaking the Compose setup as necessary.  PR coming soon...

**Comment by hkeeler** [comment]
PR #147 is now up there.  I had to do the following to get it all running.

``` bash
sbt clean
sbt assembly
docker-compose build --no-cache # ui wouldn't build without --no-cache
docker-compose up -d
```
