### ISSUE TITLE
Fix Docker Compose Setup

### ISSUE THREAD

**Issue by hkeeler** [cfpb/grasshopper#186]
Now that @awolfe76 _just_ gave a talk on how sweet our Docker Compose setup is, it'd be nice if it actually worked.  With the recent refactorings, it is most broken.  I'll work on fixing that.

**Comment by awolfe76** [comment]
@hkeeler happy to look at this if you want to work on something else. Just let me know.

**Comment by hkeeler** [comment]
Thanks @awolfe76.  I _think_ I have it working now, just have to confirm the data loading is working.  I'm also updating the docs to reflect the state of things post-refactor.  Should have a PR for this today.

**Comment by awolfe76** [comment]
:+1: I'll take a look when I see it come through.
