### ISSUE TITLE
Grasshopper UI

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#21]
Provide ui (separate repo) for grasshopper:
- Single geocode
- Batch geocode (drag & drop file)

See https://github.com/cfpb/grasshopper-ui

**Comment by awolfe76** [comment]
We've made good progress on a prototype for a UI. Definitely need to work on the drag & drop.

**Comment by jmarin** [comment]
This effort is being done in a separate repository https://github.com/cfpb/grasshopper-ui
Closing
