### ISSUE TITLE
Batch file format?

### ISSUE THREAD

**Issue by netplusdesign** [cfpb/grasshopper#27]
When someone wants to query our api and find the X,Y points for a batch of addresses... what format are they most likely to use? CSV? JSON? Other?

Do we need to specify a few formats we will accept? Or can we design something flexible enough to guess? Or some kind of data import wizard?

**Comment by hkeeler** [comment]
I think the default format for both request and response should be JSON.  If we want to support additional formats, such as CSV, we could allow API clients to specify the format by including a `Content-Type` header (ex: `Content-Type: text/csv`) on the `POST` when submitting an alternative, or an `Accept` header (ex: `Accept: text/csv`) for receiving an alternative in the response.

I'm not sure of a standard way of advertising which `Content-Type` and `Accept` values are available for a `POST`.  Probably just needs to be stated in the API Docs.

**Comment by awolfe76** [comment]
+1 @hkeeler and i agree that the docs should tell developers what's available.
