### ISSUE TITLE
Projections and transformations

### ISSUE THREAD

**Issue by wpears** [cfpb/grasshopper#29]
According to [the data spec](https://github.com/cfpb/grasshopper/blob/master/docs/data_format.md), we only accept data in NAD83. This is fine, but we almost certainly want to _serve_ WGS84 data. We don't need to, but most APIs do and most front-ends expect it.

I would imagine, then, that we should transform the data to WGS84 during the loading process. There is some complexity here, especially since the proper transformation for east of the Mississippi vs west of the Mississippi vs Hawaii etc. is different (and individual states may recommend different transformations).

The solution in my mind is to choose a transformation module and document it clearly and openly, so that if anyone at the state level notices inconsistencies they can immediately see why. The transformation module would likely just have a map of FIPS code to transformation, then call out to ogr2ogr in a subprocess for the actual transformation work.

The reason why we'd store the transformed data in elasticsearch over the raw data is because if we're accepting NAD83 but serving WGS84 (which I think we should) we'll have to transform _at some point_ no matter what. This might as well be at the time the data is loaded so we don't have to transform on every request.

As long as we keep the raw input data somewhere (like just sitting in zip files on an aws s3 instance) we can always reload data if our transformation scheme changes in the future.

@feomike @jmarin, thoughts?

**Comment by jmarin** [comment]
Ah, _GIS_. 

More seriously, you are right, we will want to serve WGS84 by default, perhaps also web mercator for web display. We might also offer the possibility to transform data on the fly if needed, by passing an EPSG code as a parameter. I'd rather do just one projection though, keep it super simple. As long as we store data in **one** known projection, we should be fine. I also think it's important to be a bit opinionated about setting expectations: grasshopper is not a GIS server, so if survey level precision is needed, this is probably not the tool/service to accomplish that, given the disparity of our data sources. I think serving one known projection and letting clients of the service deal with that is the right way to go.

**Comment by feomike** [comment]
:+1: agree wgs84.  i will be honest, i don't care which one, i care that a) it comes to us in preferably one, or alternatively one we know and is described and b) that we publish in one that most people want to consume and is described as such.  so i am fine w/ wgs 84
