### ISSUE TITLE
Output dates as ISO 8601

### ISSUE THREAD

**Issue by jmarin** [cfpb/grasshopper#33]
Have the /status endpoint output dates as [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601) 

Code to modify [here](https://github.com/jmarin/grasshopper/blob/geocodepoint/addresspoints/src/main/scala/addresspoints/api/Service.scala#L44)

**Comment by hkeeler** [comment]
I have this working, and rendering the status as follows:

``` json
{
    "status": "OK",
    "time": "2015-03-24T16:15:14Z"
}
```

So...this has spawned a few questions:
1. I've done this in UTC-based time.  Is that what we want, or should we go local time with the appropriate Timezone offset?  UTC is more "universal", but having it be DC-based time is a little easier to read.
2. I'm going down to _seconds_ precision.  Do we it down to _milliseconds_?
3. The new [Java 8 Date/Time API](http://www.mscharhag.com/2014/02/java-8-datetime-api.html) provides a much cleaner, and more _functional_ approach to dealing with dates and times in Java.  I considered taking this approach, but I wasn't sure how we feel about going full Java 8.  We claim _JDK 7 and OpenJDK versions 7 and 8 should also work_ under [Dependencies](https://github.com/cfpb/grasshopper#dependencies), but is that really a goal?  I'd prefer to take full advantage of Java 8.

**Comment by hkeeler** [comment]
Per today's standup, we're going with:
1. UTC-based time.
2. _seconds_ precision.
3. Java 8 only
