### ISSUE TITLE
basic data spec

### ISSUE THREAD

**Issue by feomike** [cfpb/grasshopper#4]
we need to write an input data spec.  there are a couple of good reasons why (e.g. eases the way for federal data sharing, makes it clear exactly what we want, makes it easier to process, moves to a common standard approach etc).  i think we should go for simple; something like;
- shapefile
- wgs 84
- fields to include
  - address
  - city
  - state
  - zip
  - alternate name
- minor metadata
  - source agency
  - publication date
  - source url
  - terms and conditions (if any)

can someone put some cycles on this and turn a proposal around by next week?  we have an immediate need.

**Comment by hkeeler** [comment]
Is goal (hope?) to get outside organizations with Geocode data (state/federal agencies, etc.) to transform their data into our format and make it available to us?  I'm all for that, but is it realistic?

Outside of that, I have a few questions about address format/style:
1. Do we want to use a less US-centric address form?  I realized _we_ only care about US addresses, but other non-US agencies may find utility in the OSS project.
   1. Zip -> Postal Code
   2. State -> Region
      
      I notice the other APIs mentioned on #1 use the term "Administrative Area Level 1".  Is this a standard naming convention for state/province/whatever?
2. How many lines of address should we allow.  In most cases 2 is enough, but I believe there are cases where you may need more.
3. Do we want to split the address part into more granular bits?  I see [Google's API](https://developers.google.com/maps/documentation/geocoding/#GeocodingResponses) splits `street_number` and `route` into discrete fields.

And finally, what data format is most reasonable?  If we go the JSON route, will that limit that adoption rate for organizations that may not have the technical staff to generate in that format?  Is CSV more appropriate?

**Comment by jmarin** [comment]
@feomike I think you have most of what's needed in your original post already. Here's my initial crack at it:
- Assume data is aggregated at the state level, and comes from state level authority or is at least divided that way. With this in mind, for address point data the naming convention could be `<STATE_FIPS_CODE>_addresspoints.shp`. Format for data is ESRI Shapefile, a common geospatial data interchange format. JSON is too bulky and CSV doesn't capture geospatial data well. 

Example: for the state of Colorado, this would be `08_addresspoints.zip` (compressed archive containing files that make up a valid Shapefile) 
- Projection must be defined. Data in Global Coordinate System, North American Datum of 1983 (GCS NAD83). Include a .prj file with each shapefile, should have the following contents:

```
GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6
378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]]
```
- Field definition:

ID: Unique number, automatically assigned (primary key, Integer)
SHAPE: Geometry (Shapefile format)
NUMBER: House number. Includes possibles prefix or suffix. Varchar (50)
ADDRESS: Complete street address. Includes secondary address unit designators (apt., building, unit, etc). Varchar(255)
ALT_ADDR: Alternate address, if appropriate. Varchar(255)
CITY. Varchar(255)
STATE. State abbreviation. Char(2)
ZIP5. Vachar(5)
DATE. Varchar(255). Timestamp for the record, in ISO 8601 format

Example:

```
101 Main St Apt # 101 Springfield VA 22162
```

where:

```
101 --> NUMBER
Main St Apt # 101 --> ADDRESS
Springfield --> CITY
VA --> STATE
22162 --> ZIP5
```

For guidance on street address formatting, this is a good starting point (we don't need everything uppercase though)

http://pe.usps.gov/cpim/ftp/pubs/Pub28/pub28.pdf

**Comment by feomike** [comment]
responding to @hkeeler 
- it is a hope and i think (perhaps naively) realistic.  perhaps many won't but some will transform for us.
- i want to say i am agnostic about US vs. more global standards, but i am not.  we are building something US centric.  i am good w/ staying that way.
- i actually prefer 1 full text address field.  @jmarin has outlined two; am guessing he has a reason, we should flesh that out
- i was thinking we should go with lumping rather than splitting in this case, and leave the heavy lifting to the search algorithm.  again, we should debate. my intent at version 0.01 is for a request to another specific agency.  it will be a good notion of the first external feedback we get
- i agree that shape is likely the first step in a format.  in some places, it will fail (e.g. greater than the 2 gig limit), in which case we might got w/ fips counties for other places (might also fail for say LA County).  

more coming ...

**Comment by jmarin** [comment]
The spec is here https://github.com/cfpb/grasshopper/blob/master/docs/data_format.md
