### ISSUE TITLE
Using score for choosing a data source

### ISSUE THREAD

**Issue by debseidner** [cfpb/grasshopper#65]
As a geocoding system, I need to recognize the hierarchy between the different data sources so that I can choose which data source is best to use for a particular search

**Comment by hkeeler** [comment]
We're not really taking on _scoring_ per se for [M3](https://github.com/cfpb/grasshopper/milestones/M3), right?  I think we decided of something simple like:
1. Address points are best.
2. If not available, use TIGER lines.
3. If neither available, fail.

**Comment by awolfe76** [comment]
:+1: 

Yeah, that was my take as well. Scoring doesn't matter if we returning only 1 result or nothing.
So **no** relevancy or score in the response.

**Comment by jmarin** [comment]
Removing the M3 label. Keeping ticket in backlog
